### ISSUE TITLE
Unable to install Winusers-1.0 on 2.4.1

### ISSUE THREAD

**Issue by mfestrada** [PluginsOCSInventory-NG/winusers#10]
Hi all,

I'm trying to install this plugin going by the installation instructions on the release page (https://github.com/PluginsOCSInventory-NG/winusers/releases/latest), and after downloading the winusers.zip and placing it in the listed directory (/usr/share/ocsinventory-reports/ocsreports) the plugins manager displays "There is currently no plugin available for installation".  I've tried restarting apache, but to no avail.  

Also, the only reason I'm installing this plugin is because I'm having an issue with the Connected Users field being blank for a small number of hosts within my network and I can't understand why.

Thank you,
Michael Estrada

**Comment by steph78630** [comment]
hi,

for install plugins, the right directory for plugin.zip is : /usr/share/ocsinventory-reports/ocsreports/download

Regards, Stéphane

**Comment by mfestrada** [comment]
Thank you for your prompt reply!! That did the trick! :smile:
