### ISSUE TITLE
 problem with plugin winusers 2.2

### ISSUE THREAD

**Issue by MarcoTorres92** [PluginsOCSInventory-NG/winusers#18]
Good morning everyone, the problem I have is that when I run an inventory and see the log file, I get output errors, I upload a log image, it will also be possible to see users who are under active directory, thanks.

![image](https://user-images.githubusercontent.com/66989169/86268910-92bf9280-bb8e-11ea-8b6e-50335a6f6211.png)

**Comment by gillesdubois** [comment]
Hi,

If the plugin encountered an error you will have a file named "pluginname".ps1.xml that will be kept in %programdata%/OCS Inventory NG/Agent/

Is there something in this file ?

Regards,
Gilles Dubois.

**Comment by pintyoke** [comment]
Hi,

I have this mistake too. Hungarian language Windows:

Get-LocalGroupMember : Group Administrateurs was not found.At C:\Program Files\OCS Inventory Agent\plugins\winusers.ps1:3 char:16+     $admingroup = Get-LocalGroupMember -Group "Administrateurs"+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    + CategoryInfo          : ObjectNotFound: (Administrateurs:String) [Get-LocalGroupMember], GroupNotFoundException    + FullyQualifiedErrorId : GroupNotFound,Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand Get-LocalGroupMember : Group Administrateurs was not found.At C:\Program Files\OCS Inventory Agent\plugins\winusers.ps1:3 char:16+     $admingroup = Get-LocalGroupMember -Group "Administrateurs"+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    + CategoryInfo          : ObjectNotFound: (Administrateurs:String) [Get-LocalGroupMember], GroupNotFoundException    + FullyQualifiedErrorId : GroupNotFound,Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand Get-LocalGroupMember : Group Administrateurs was not found.At C:\Program Files\OCS Inventory Agent\plugins\winusers.ps1:3 char:16+     $admingroup = Get-LocalGroupMember -Group "Administrateurs"+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    + CategoryInfo          : ObjectNotFound: (Administrateurs:String) [Get-LocalGroupMember], GroupNotFoundException    + FullyQualifiedErrorId : GroupNotFound,Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand Get-LocalGroupMember : Group Administrateurs was not found.At C:\Program Files\OCS Inventory Agent\plugins\winusers.ps1:3 char:16+     $admingroup = Get-LocalGroupMember -Group "Administrateurs"+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    + CategoryInfo          : ObjectNotFound: (Administrateurs:String) [Get-LocalGroupMember], GroupNotFoundException    + FullyQualifiedErrorId : GroupNotFound,Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand Get-LocalGroupMember : Group Administrateurs was not found.At C:\Program Files\OCS Inventory Agent\plugins\winusers.ps1:3 char:16+     $admingroup = Get-LocalGroupMember -Group "Administrateurs"+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    + CategoryInfo          : ObjectNotFound: (Administrateurs:String) [Get-LocalGroupMember], GroupNotFoundException    + FullyQualifiedErrorId : GroupNotFound,Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand <WINUSERS><NAME>AlapÃ©rtelmezett fiÃ³k</NAME><TYPE>Local user</TYPE><SIZE>0,00</SIZE><LASTLOGON></LASTLOGON><DESCRIPTION>A rendszer Ã¡ltal kezelt felhasznÃ¡lÃ³i fiÃ³k.</DESCRIPTION><STATUS>Disabled</STATUS><USERMAYCHANGEPWD>True</USERMAYCHANGEPWD><PASSWORDEXPIRES></PASSWORDEXPIRES><SID>S-1-5-21-2309963293-3786387737-2003613890-503</SID></WINUSERS><WINUSERS><NAME>ptk</NAME><TYPE>Local user</TYPE><SIZE>11,63</SIZE><LASTLOGON>07/20/2020 09:02:43</LASTLOGON><DESCRIPTION></DESCRIPTION><STATUS>Enabled</STATUS><USERMAYCHANGEPWD>True</USERMAYCHANGEPWD><PASSWORDEXPIRES></PASSWORDEXPIRES><SID>S-1-5-21-2309963293-3786387737-2003613890-1001</SID></WINUSERS><WINUSERS><NAME>Rendszergazda</NAME><TYPE>Local user</TYPE><SIZE>0,00</SIZE><LASTLOGON></LASTLOGON><DESCRIPTION>BeÃ©pÃ­tett fiÃ³k a gÃ©p/tartomÃ¡ny felÃ¼gyeletÃ©hez</DESCRIPTION><STATUS>Disabled</STATUS><USERMAYCHANGEPWD>True</USERMAYCHANGEPWD><PASSWORDEXPIRES></PASSWORDEXPIRES><SID>S-1-5-21-2309963293-3786387737-2003613890-500</SID></WINUSERS><WINUSERS><NAME>VendÃ©g</NAME><TYPE>Local user</TYPE><SIZE>0,00</SIZE><LASTLOGON></LASTLOGON><DESCRIPTION>BeÃ©pÃ­tett fiÃ³k a gÃ©p/tartomÃ¡ny vendÃ©gkÃ©nt valÃ³ elÃ©rÃ©sÃ©hez</DESCRIPTION><STATUS>Disabled</STATUS><USERMAYCHANGEPWD>False</USERMAYCHANGEPWD><PASSWORDEXPIRES></PASSWORDEXPIRES><SID>S-1-5-21-2309963293-3786387737-2003613890-501</SID></WINUSERS><WINUSERS><NAME>WDAGUtilityAccount</NAME><TYPE>Local user</TYPE><SIZE>0,00</SIZE><LASTLOGON></LASTLOGON><DESCRIPTION>A rendszer Ã¡ltal kezelt Ã©s hasznÃ¡lt felhasznÃ¡lÃ³i fiÃ³k a Windows Defender alkalmazÃ¡sÅr forgatÃ³kÃ¶nyveihez.</DESCRIPTION><STATUS>Disabled</STATUS><USERMAYCHANGEPWD>True</USERMAYCHANGEPWD><PASSWORDEXPIRES>06/17/2020 08:10:00</PASSWORDEXPIRES><SID>S-1-5-21-2309963293-3786387737-2003613890-504</SID></WINUSERS>

**Comment by gillesdubois** [comment]
Hi,

Please check : https://github.com/PluginsOCSInventory-NG/winusers/issues/19

Admin group name is not localized and need to be edited manually in the mean time.

Regards,
Gilles Dubois.
