### ISSUE TITLE
Alter name group

### ISSUE THREAD

**Issue by josantana88** [PluginsOCSInventory-NG/winusers#19]
Name group is not right

	$admingroup = Get-LocalGroupMember -Group "Administrateurs"

Name group correct 

	$admingroup = Get-LocalGroupMember -Group "Administrators" or 	$admingroup = Get-LocalGroupMember -Group "Administradores" (Português Brazil)

**Comment by gillesdubois** [comment]
Hi,

We are aware of the problem. In the meantime you will have to edit the group name manually before deploying the PS File.

Regards,
Gilles Dubois.

**Comment by CraigFox** [comment]
Changing the code to use the SID instead of the group's name will resolve the issue.  The SID is well know and will work on all languages.

	$admingroup = Get-LocalGroupMember -SID "S-1-5-32-544"

**Comment by gillesdubois** [comment]
Hi,

This problem has been fixed with the PR listed above.

Regards,
Gilles.
