### ISSUE TITLE
measure-object : Length porperty

### ISSUE THREAD

**Issue by esimonin** [PluginsOCSInventory-NG/winusers#20]
Hi 

we have an error in PS running

measure-object : La propriété « length » est introuvable dans les entrées d’objets.
Au caractère C:\Program Files\OCS Inventory Agent\Plugins\winusers.ps1:20 : 42
+ ... ci -path $pth -recurse | measure-object -property length -sum).sum /1 ...
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument : (:) [Measure-Object], PSArgumentException
    + FullyQualifiedErrorId : GenericMeasurePropertyNotFound,Microsoft.PowerShell.Commands.MeasureObjectCommand

**Comment by ajavor** [comment]
Requires powershell 7.1 for this command
(Windows 10 has powershell 5.1 by default).

Is there a workaround for this problem or do I need to update the PS to the latest version on all agent stations?

**Comment by ajavor** [comment]
Add the **-file** parameter in the .ps1 script:

as below:

`"{0:n2}" -f ((gci -path $pth -recurse -file | measure-object -property length -sum).sum /1mb)`





Unfortunately, the above command does not take into account hidden subfolders (so the calculated value is false).
To take them into account, you need to use an additional parameter:
**-force**

as below:
`"{0:n2}" -f ((gci -path $pth -recurse -file -force | measure-object -property length -sum).sum /1mb)`

Unfortunately, when we use the -force parameter, we get a lot of PermissionDenied errors.
